#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const REPLACEMENT_STRING = '/* REPLACE ME! */';
const FILE_TEMPLATE = `/**
 * Copyright (c) ${new Date().getFullYear()} Jellyfin Contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * NOTE: This file is auto-generated by scripts/generate_langs.js
 */

const languages: Record<string, { default: Record<string, string> }> = {
	${REPLACEMENT_STRING}
};

export default languages;
`;
const getLanguageString = langFile => {
	let langKey = langFile.replace('.json', '').replaceAll('_', '-');
	if (langKey.includes('-')) {
		langKey = `'${langKey}'`;
	}
	return `${langKey}: require('./langs/${langFile}')`;
};

const langsDir = path.join(__dirname, '..', 'langs');
const languages = [];
for (const langFile of fs.readdirSync(langsDir)) {
	// console.log(langFile);
	const translations = JSON.parse(fs.readFileSync(path.join(langsDir, langFile)));
	if (Object.keys(translations).length < 2) {
		console.warn(`Skipping ${langFile} (insufficient translations)`, JSON.stringify(translations));
		continue;
	}
	languages.push(getLanguageString(langFile));
}

const output = FILE_TEMPLATE.replace(REPLACEMENT_STRING, languages.join(',\n\t'));
fs.writeFileSync(path.join(__dirname, '..', 'languages.ts'), output);
